### ISSUE TITLE
Consider renaming

### ISSUE THREAD

**Issue by bragefuglseth** [flattool/flattool-gui#15]
This issue is mostly relevant if you’d like as much design integration into GNOME as possible. Feel free to close it if it feels like too much work or if it’s irrelevant.

GNOME’s [app name guidelines](https://developer.gnome.org/hig/guidelines/app-naming.html) discourages made-up word combinations, which the current app name has. To make it match other GNOME app names and follow the guidelines, we could find one or two simple nouns related to the domain/purpose of the app, and use those.

I’d be happy to assist if this is considered wanted and actionable.

**Comment by AtiusAmy** [comment]
I thought it was pretty similar to Flatseal, and it works for them

also i'm such a big fan of you-

**Comment by heliguy4599** [comment]
Hello! First let me say sorry for the delay in response.
Anyways, I would like to agree with what Amy said, I figured people were happy with Flatseal, and Flattool is very similar in concept. Personally I do not see an issue with the name but if you have something in mind that I haven't thought of I'm open to hear it.

Thanks for your interest in my project!

**Comment by runarcn** [comment]
Imo Flattool should follow these guidelines well enough, considering that apps such as Wike are accepted (unless Wike is a word in a language I was unable to find, of course). However, it could be an idea to either change the icon to a wrench or find another name which is easier to get an icon for.

If Flattool is kept, here're two *very* shitty mockups for how another logo could look. Please find someone who isn't doing this on a laptop mid class if this looks cool. The second one is inpsired by the GNOME Disks app.

![flattool-1](https://github.com/flattool/flattool-gui/assets/52424029/86a954a7-c448-434f-9816-8bc404cf27dd)
![flattool-1](https://github.com/flattool/flattool-gui/assets/52424029/1b1c6971-c051-4b48-a886-e7b90d73514e)

Worth noting that I know little of GNOME and naming outside of the provided guidelines, so I could very well be misunderstanding

**Comment by runarcn** [comment]
update: apparently the background got black on the second one, so here's a more visible version

![image](https://github.com/flattool/flattool-gui/assets/52424029/687e9a90-2e1d-4afe-a0ea-90d99df87b70)

**Comment by bragefuglseth** [comment]
Technically Flatseal and Wike aren't following the guidelines, but at this point their names are so established that it's hard to change. I think there are a lot of worse app names than Flattool out there, fortunately, so it's not *urgent*, but

**Comment by bragefuglseth** [comment]
These are some possible names that follow the guidelines:

- Warehouse
- App Crane
- Forklift
- App Shelf
- Catalog

I think all of these could be paired pretty easily with e.g. one of the following app summaries:
- "Manage your flatpaks"
- "Inspect your app library"

**Comment by bragefuglseth** [comment]
The icon is already well executed with GNOME's app icon style, so I figured you probably don't need help with designing a new one if the name changes, but feel free to reach out to us in the [GNOME App Icon Design](https://matrix.to/#/#appicondesign:gnome.org) room on Matrix for help/feedback related to both naming and icon design :grin:

**Comment by kra-mo** [comment]
> The current app icon is already well executed and follows GNOME's app icon style

Not really. The Flatpak logo thrown in there doesn't look great, there's meaningless gradients on surfaces that don't warrant them and it does not look good against dark backgrounds. Though these could be easily fixed.

**Comment by kra-mo** [comment]
Not to mention the shape being wonky, but that's whatever

**Comment by bragefuglseth** [comment]
As I said, the app icon design room is probably a better place to have that discussion in this GitHub thread, as those discussions tend to get long and detailed. It’s not the main focus of this issue either

**Comment by kra-mo** [comment]
For sure, I just wanted to point these out

**Comment by heliguy4599** [comment]
After spending a few days with designers and friends, I am rebranding the app to Warehouse with the accompanying icon.
