### ISSUE TITLE
Trashing leftover data does not work

### ISSUE THREAD

**Issue by Kuchenmampfer** [flattool/flattool-gui#7]
![Screenshot_20230902_225734](https://github.com/flattool/flattool-gui/assets/79256346/f4883be4-80e4-435c-8407-6f19d30d7841)
I selected about two thirds of the leftover data apps and clicked the `Trash` Button. This resulted in the shown error message for every single app. I don't think any of it got deleted.

**Comment by heliguy4599** [comment]
This might sound silly but what DE are you on?
Follow up question, does the command `gio` exist on your system?

**Comment by Kuchenmampfer** [comment]
I am on Crystal with KDE and `gio` exists, yes

**Comment by heliguy4599** [comment]
Ok that's interesting then. What happens if you run my app with the terminal and try the same operation? What output, if any, do you get?

**Comment by Kuchenmampfer** [comment]
no output at all :/

**Comment by heliguy4599** [comment]
...huh
The app's data is stored within `~/.var/app/` yes?

**Comment by heliguy4599** [comment]
I'm dumb, it has to be there because there is no other way for the app to see those files to show to you.

**Comment by heliguy4599** [comment]
I found the issue. I used "gio remove" instead of "gio trash". Oops
